# Generated by Django 5.0.1 on 2024-01-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/'),
        ),
    ]
