# Generated by Django 5.0.1 on 2024-01-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_city_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cidades/'),
        ),
    ]
