# Generated by Django 5.0.1 on 2024-01-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_alter_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state', to='lugares.state'),
        ),
    ]
