# Generated by Django 5.0.1 on 2024-01-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0007_category_alter_local_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='cep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
