# Generated by Django 5.0.1 on 2024-01-25 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0008_local_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_contact', to='lugares.contact'),
        ),
        migrations.AlterField(
            model_name='local',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_location', to='lugares.location'),
        ),
    ]
