# Generated by Django 5.0.1 on 2024-01-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0010_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
    ]
