# Generated by Django 5.0.1 on 2024-01-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0011_remove_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='cep',
        ),
    ]
