# Generated by Django 5.0.1 on 2024-01-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0012_remove_local_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
